### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gabrielR0**
small typos

### CODE REVIEW

**Comment by anselal** [comment]
Those ain't no typos

**Comment by anselal** [comment]
Thnx anyway

**Comment by gabrielR0** [comment]
Well, I've tried after an update :)
python manage.py --help
Usage: manage.py [OPTIONS] COMMAND [ARGS]...

Options:
  --version  Show the flask version
  --help     Show this message and exit.

Commands:
  **create-admin**  Create admin user if not exist with default password...
  **create-db**     Create database.
  db            Perform database migrations.
  format        Runs the yapf and isort formatters over the project.
  routes        Show the routes for the app.
  run           Runs a development server.
  shell         Runs a shell in the app context.
  **update-db**     Update miner models and settings.

**Comment by anselal** [comment]
Well, I get the same output but with underscores.
And I always use underscores, and the code is written with underscores.
See eg. https://github.com/anselal/antminer-monitor/blob/b7f75c84ffc0a2883eb2a92a0136bc5d8d9ede37/manage.py#L16

the method name contains an underscore and not a dash.

**Pull request closed without merging**
