### PR TITLE
Refactor RFC

### PR DESCRIPTION
**Pull request by sergioclemente**
Trying to extract bitmain miner logic from antminer.py, let me know if this totally out of whack. The idea here is to allow easier integration with Avalon miners later on. I was planning to re-use the same view.

### CODE REVIEW

**Comment by sergioclemente** [comment]
@anselal just making sure you saw this. 

There is a minor bug that I missed (I've updated the temp threshold to 70), but I can update once you send the first batch of feedback in. 

This change is critical for adding support for avalon, which I got working already and just waiting on this change to send the next batch of changes.

**Comment by anselal** [comment]
Hi there,

I am not sure i understand your code. I need more time to read through it.
I am working on an API right now, and on a new structure. I want to split the app into blueprints so the entire structure will change.
After that I will review your changes. Sorry about the delay

**Comment by sergioclemente** [comment]
Sounds good, might change might become irrelevant then. Most of it is extract the logic out.

**Comment by anselal** [comment]
The API itself extracts the logic. Maybe it will need some work for Avalon support. You can work on it after i push it to the codebase

**Comment by sergioclemente** [comment]
yup. thats what i figured when you described API.

currently I have it working for 741, waiting on the 821 units to arrive to make sure it works also. I don't have a 761 unit to test so that might fall under future work.

**Pull request closed without merging**
