### PR TITLE
Show an indication of high temperature before the actual warning

### PR DESCRIPTION
**Pull request by sergioclemente**
This is to indicate a warning before the actual temps reaches 80. Let me know if its something you interest.

### CODE REVIEW

**Comment by sergioclemente** [comment]
@anselal let me know if this change is interesting or i should revert it

**Comment by anselal** [comment]
Sorry for the delay, I think the notification got lost in my emails.
Anyway, I do something similar at 

https://github.com/anselal/antminer-monitor/blob/0a2b3165b09123f1118f6c007052b0bb5a34f681/app/views/antminer.py#L115-L118

but I just display a warning. The code looks good to me. I will try it out on my local copy and let you know :wink:

**Comment by sergioclemente** [comment]
80 degrees is already pretty hot and I was wondering if it made sense to show a warning before the actual message. Thoughts?

**Comment by anselal** [comment]
Actually 80 is not too hot if you consider that the S9 temps are at 70 at the default frequency. So showing a warning at the default temps isn't such a good idea. The miners can run almost without any error at 80 degrees thus showing just a warning

What we can do is give the ability to the user to change this value. But I will open another issue about this.

Thoughts ?

**Comment by sergioclemente** [comment]
Yes, i think each unit should have a configurable temperature for ideal and error temps. lets open a separate issue and i will close this request

**Comment by anselal** [comment]
This is already implemented by a fellow coder who wants to stay anonymous for now. I will merge it after i finish the API

**Pull request closed without merging**
