### PR TITLE
Couple of changes

### PR DESCRIPTION
**Pull request by sergioclemente**
* Adds http_admin_host_port to allow setting a different configuration for the antminer console (Imagine this is useful for cases like you specify a remote ip/port)
* Updates hashrates so that they are > 1000. e.g. 19000MH/s will be updated to 19GH/s
* Check if the device is in error state by checking status <> 'S'. This is safer than checking for = 'error'

### CODE REVIEW

**Comment by sergioclemente** [comment]
I added more stuff which I don't think its generic enough so let me know what you would like to reuse and I can create a pull request for just the necessary part

**Comment by hansje69** [comment]
I would also like to see a <port> option... as I run  all my miners same network ip, but different ports

**Comment by sergioclemente** [comment]
I think from the other thread @anselal  doens't like the idea of exposing to the public net. I guess I will just keep as an isolated fork

**Comment by anselal** [comment]
@sergioclemente dont get upset. Since many users requested it we will implement it. But we will have to figure out if the users forward the RPC port or the WebUI port, or both

**Comment by anselal** [comment]
@sergioclemente Thank you again for taking the time to contribute to my project, I really appreciate work you've done here. I mean you really did some work there but your commits are not properly structured. 

E.g. at c13a133 you say `Properly check for errors with <> 'S'` but you have committed more changes so I can't merge only the ones I want. 

( I won't comment on particular line this time )
To be honest the particular commit hasn't any changes I want to merge and I will tell you why
  - There was no need to rename the IP field in the database
  - The remote port is the http port instead of the RPC port
  - You link only the http port in the inactive-miners-list instead of IP:PORT (minor bug)
  - Checking for status 'S' is the proper way to go if you have access to the cgminer-api. If there is a problem with the connection or cgminer-is not running either because of an error or because there isn't a miner behind that IP address, then the key `['STATUS'][0]['STATUS']` doesn't exists on the JSON and looking for this key will raise an exception.
This is why I have added it at https://github.com/anselal/antminer-monitor/blob/0a2b3165b09123f1118f6c007052b0bb5a34f681/app/pycgminer/pycgminer.py#L30-L31

At commit a8b1052 you do two things:
  - Rename remote_host_port to http_admin_host_port
  - Convert units from 19000 MH/s to 19 GH/s for example

I think the method `update_unit_and_value` is better than a bunch of classes. One method simply is more readable. 

Your commits should be cleaner and smaller and apply only one change at a time so we can more efficiency manage our work !!!

I will review again your changes to see how we will proceed !!!

PS: contact me via email so we can chat better outside github.

**Comment by sergioclemente** [comment]
> The remote port is the http port instead of the RPC port
Well, RPC custom port is not a feature i need. the custom http host/port would be as I want to access this remotely and thats one way of doing it. Do you want the option to customize the http host/port? I can submit a custom cl.

> Checking for status 'S'
Agreed

> Convert units from 19000 MH/s to 19 GH/s for example
Do you like this change? I can make the one method version and submit 1 cl

PS. Please be more prompt on reviewing this. it started small but at one point i gave up and thought you were not interested. its not encouraging behavior.

**Comment by gnanet** [comment]
@sergioclemente from my experience, if you contribute to a project by creating pull requests, it is advised to follow these simple things:

1. open a separate pull-request for every separate topic you changed
it is better to have a lot of small merged PRs, than a huge PR denied because of small things in it ;)
2. try to avoid changes in indenting or linebreaks, if the change is not affecting the way code works, or the pull-request is not coding-style related
3. only open a pull-request after you tested all the changes on your fork
This ensures for example that micro-changesets does not get into the pull-request, which only create and remove the same debugging code
4. if you think a pull-request you opened needs changes, because you developed further, you can close your own PR, and place a new one with the reworked changes
5. be patient
Maintainers are often people, who are working on their projects in their spare time, which is not a constant thing, and sometimes long time passes, before you see a response, but that does not mean they are not interested


its only my 2 cents

**Comment by anselal** [comment]
> Convert units from 19000 MH/s to 19 GH/s for example
> Do you like this change? I can make the one method version and submit 1 cl

@sergioclemente Yes, I would like this method on my app :+1: 
Please create a new PR for this and I will review it.

Sorry if my reply took too long, for your taste. I get notified on every new issue/pull request, but your PRs were a mess and I needed some time to see what you did there. Please try to follow @gnanet advises as I totally agree with them.

**Pull request closed without merging**
