### PR TITLE
Add auto detection of miner model

### PR DESCRIPTION
**Pull request by sergioclemente**
Title says all.

### CODE REVIEW

**Comment by anselal** [comment]
Hi,

looks a lot like my implementation. The main difference is that I added this piece of code together with an auto-discovery feature. I created a form that gives the user the opportunity to scan an IP range for miners and adds the found miners after a model autodetection

**Comment by anselal** [comment]
My code looks like this:

```py
@app.route('/add', methods=['POST'])
def add_miner():
    miner_ip = request.form['ip']
    miner_model_id = request.form.get('model_id')
    miner_remarks = request.form['remarks']

    # exists = Miner.query.filter_by(ip="").first()
    # if exists:
    #    return "IP Address already added"

    add_miner(miner_ip, miner_model_id, miner_remarks)

    return redirect(url_for('miners'))

def add_miner(miner_ip, miner_model_id, miner_remarks):
    try:
        miner = Miner(ip=miner_ip, model_id=miner_model_id, remarks=miner_remarks)
        db.session.add(miner)
        db.session.commit()
        flash("Miner with IP Address {} added successfully".format(miner.ip), "success")
    except IntegrityError as e:
        db.session.rollback()
        flash("IP Address {} already added".format(miner_ip), "error")

@app.route('/batch/add/<string:subnet>/<int:start_ip>/<int:end_ip>')
def batch_add(subnet, start_ip, end_ip):
    #subnet = '192.168.1'
    #start_ip = 102
    #end_ip = 110

    miners = {}
    subnet = subnet + "."
    
    while start_ip <= end_ip:
        ip = subnet + str(start_ip)
        miner_stats = get_stats(ip)
        print("Quering IP %s" % ip)
        if miner_stats['STATUS'][0]['STATUS'] == 'error':
            print("Error adding IP %s" % ip)
            start_ip += 1
            continue
        miner_type = miner_stats['STATS'][0]['Type'].split(' ')[1]
        miners.update({ip: {"miner_type": miner_type}})
        print("Added IP %s, type %s" % (ip, miner_type))
        model = MinerModel.query.filter_by(model=miner_type).first()
        add_miner(ip, model.id, "")

        start_ip += 1
        
    return redirect(url_for('miners'))
```

**Comment by sergioclemente** [comment]
Can you call my code from your new code? It would make integration easier plus other folks can use as we don't know when you are going to submit this changes.

**Comment by sergioclemente** [comment]
PS. Integration would be easier because my code already supports avalon

**Comment by anselal** [comment]
> Can you call my code from your new code? It would make integration easier plus other folks can use as we don't know when you are going to submit this changes.

Don't have quite the time to test it right now

**Comment by shotaatosh** [comment]
Auto detect would be great but I think choosing beforehand what miners must be added will be more useful, I mean if I have to add 40 D3s instead of auto detection it would be easier to just tick a 'D3' and start adding

**Comment by anselal** [comment]
@shotaatosh This is way more easier to implement

**Comment by anselal** [comment]
I see you added a _CachedHttpRequest_ and a profits page. Nice work. How exactly does the _CachedHttpRequest_ work and what does it cache ?

**Comment by sergioclemente** [comment]
Because I make some http requests to get BTC/LTC/etc price I cache them so that for many models the page loading time gets faster.

**Comment by anselal** [comment]
Oh man, a lot of merge conflicts . Anyways, this is what I got so far
 - The update. db script doesn't work because you updated the models (removed the _Settings_ model etc.)
 - The auto-model-recognise feature does not recognise the S7 for some reason. (I also have an auto-model-recognised feature in my local branch and it works great. It also scans your network for miners so there is no need to add them one by one ;)) 
 - I really liked your profit page although I don't understand what the "Number of Devices" column stands for. Is it supposed to calculate the global number of devices currently mining based on the networks difficulty ?
 - Nice touch splitting the templates and including them in the base html
 - There is an __init__.py file inside the templates folder which is a clone of another file

**Comment by anselal** [comment]
I have inform you that I finished with refactoring the app into blueprints but i won't push the changes yet because i want to close some issues before the next release.
Also I will have to update the README because I changed the way yo start the app.
Basically instead of `python manager.py runserver` you start it with `python manager.py run` but this is only a development server. The best solution is to start the app with gunicorn.
With gunicorn I updated the logging mechanism, now everything is logged using gunicorn but there are some tweaks I wanna do.
I will try to document all the changes I made and want to do in an issue so we can discus them all and build a good structure.

**Comment by sergioclemente** [comment]
Sounds good thanks for the update. Looking forward for your changes.

Some notes:
* Not surprised the auto update doesn't work with S7 as I don't have one. We need a fallback page anyway for cases uses wants to force (See A3 model) or we can't detect.
* Number of devices was something I've created to myself to have an idea of: If all devices were like mine, how many of those would be? its essentially network_hash_rate/my_hash_rate
* I liked the way you did templating, I want to integrate parts of your code too.

I think I can close this based on your last comment.

**Comment by anselal** [comment]
I also opened two other issues #80 and #81 and locked them so only we two can write.

**Pull request closed without merging**
